### ISSUE TITLE
segfault mapping reads to reference

### ISSUE THREAD

**Issue by MichelMoser** [thegenemyers/DALIGNER#27]
Hi, 
I would like to map some P4C6 to a reference and run into segmentation faults. 
Could i get some help or tutorial how to do propper mapping with daligner/HPCmapper? 

Thank you!
Michel

DAM : 
```
              1 contigs      out of               1  (100.0%)
        158,794 base pairs   out of         158,794  (100.0%)

        158,794 average contig length
```
DB: 
```
      1,594,871 reads        out of       1,594,871  (100.0%)
 14,562,600,633 base pairs   out of  14,562,600,633  (100.0%)

          9,130 average read length
          5,510 standard deviation
```

Command used: 
```
/home/mmoser/DAZZLER/DALIGNER/daligner -A -v -b -k20 -h50 -e.85 -M8 Pax.chloro ../15smrtex
```
gdb run shows: 

```
Building index for Pax.chloro

   Kmer count = 158,775
   Using 0.00Gb of space
[New Thread 0x2aae13bf1700 (LWP 96553)]
[Thread 0x2aae13bf1700 (LWP 96553) exited]
[New Thread 0x2aae13df2700 (LWP 96554)]
....
....
[Thread 0x2aae141f4700 (LWP 96573) exited]
[Thread 0x2aae13ff3700 (LWP 96574) exited]
[Thread 0x2aae13bf1700 (LWP 96576) exited]
[Thread 0x2aae13df2700 (LWP 96575) exited]
   Index occupies 0.00Gb

Building index for c(Pax.chloro)

   Kmer count = 158,775
   Using 0.00Gb of space
[New Thread 0x2aae13bf1700 (LWP 96577)]
[Thread 0x2aae13bf1700 (LWP 96577) exited]
[New Thread 0x2aae13df2700 (LWP 96578)]
[Thread 0x2aae13df2700 (LWP 96578) exited]
[New Thread 0x2aae13ff3700 (LWP 96579)]
[Thread 0x2aae13ff3700 (LWP 96579) exited]
....
....
[Thread 0x2aae13ff3700 (LWP 96598) exited]
[Thread 0x2aae13bf1700 (LWP 96600) exited]
   Index occupies 0.00Gb

Building index for 15smrtex
[Thread 0x2aae13df2700 (LWP 96599) exited]

   Kmer count = 1,647,396,196
   Using 49.10Gb of space
[New Thread 0x2aae13bf1700 (LWP 96601)]
[New Thread 0x2aae13df2700 (LWP 96602)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x2aae13df2700 (LWP 96602)]
0x00000000004054c2 in biased_tuple_thread (arg=0x7ffffff85698) at filter.c:577
577             while ((x = s[p]) != 4)
```

gdb backtrace: 

```
#0  0x00000000004054c2 in biased_tuple_thread (arg=0x7ffffff85698) at filter.c:577
#1  0x00002aaaaacd85aa in start_thread () from /software/lib64/libpthread.so.0
#2  0x00002aaaab2fb87d in clone () from /software/lib64/libc.so.6
```

**Comment by thegenemyers** [comment]
I think you blew memory.  The DB should be broken down into smaller 
blocks and
each block run against the chloroplast sequence.

I do apologize however, the program should give you an error message and 
exit
gracefully -- I'm not sure how that happened.

    -- Gene

**Comment by MichelMoser** [comment]
Thank you, just saw that problem has been reported before. 
Runs like a charm with blocksize 200Mb.
